# Generated by Django 6.0.6 on 2026-07-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lcd',
            options={'ordering': ['-created_at'], 'verbose_name': 'LCD', 'verbose_name_plural': 'LCD'},
        ),
    ]
