# Generated by Django 6.0.6 on 2026-07-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCD', '0002_alter_lcd_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcd',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
