# Generated by Django 6.0.6 on 2026-07-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCD', '0004_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcd',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='LCD.brand'),
        ),
    ]
