# Generated by Django 6.0.6 on 2026-07-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCD', '0006_brand_slug_brand_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcd',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcd', to='LCD.brand'),
        ),
    ]
